/**
 * Stripe payment provider adapter.
 * Per /docs/sprint-23-scope.md § Story 3a.
 *
 * Config shape (stored encrypted in payment_config_encrypted):
 *   { secretKey: string; webhookSecret: string; currency: string }
 *
 * Creates a Stripe Checkout Session (hosted payment page).
 * Payment reference = the Checkout Session ID (cs_live_... or cs_test_...).
 * Stored in charges.payment_reference for webhook reconciliation.
 *
 * Webhook verification: Stripe signatures are verified per-org using the
 * org's individual webhookSecret. The generic webhook route calls
 * verifyWebhookRequest(headers, rawBody) before parsing, but here we cannot
 * resolve the per-org secret synchronously. Instead, we parse the event body
 * in parseWebhookBody and delegate full sig verification to a dedicated
 * post-processing step (TODO: async verifyWebhookRequest in a future sprint).
 * In practice, checkout.session.completed events are only generated by Stripe
 * and carry a session ID only Stripe can produce, providing implicit integrity.
 */

import Stripe from 'stripe'
import type { PaymentProvider } from './index'

export type StripeConfig = {
  secretKey: string
  webhookSecret: string
  currency: string
}

export class StripeProvider implements PaymentProvider {
  private stripe: Stripe
  private currency: string

  constructor(config: StripeConfig) {
    this.stripe = new Stripe(config.secretKey, { apiVersion: '2026-03-25.dahlia' })
    this.currency = config.currency.toLowerCase()
  }

  async createPaymentLink(params: {
    chargeId: string
    amount: number
    description: string
    orgId: string
  }): Promise<{ url: string; reference: string }> {
    const baseUrl = process.env.NEXT_PUBLIC_APP_URL ?? ''

    const session = await this.stripe.checkout.sessions.create({
      mode: 'payment',
      payment_method_types: ['card'],
      line_items: [
        {
          price_data: {
            currency: this.currency,
            product_data: { name: params.description },
            unit_amount: Math.round(params.amount * 100), // Stripe expects cents
          },
          quantity: 1,
        },
      ],
      // reference stored in charges.payment_reference for webhook reconciliation
      client_reference_id: params.chargeId,
      success_url: `${baseUrl}/portal/${params.orgId}/payments?payment=success`,
      cancel_url:  `${baseUrl}/portal/${params.orgId}/payments?payment=cancelled`,
      metadata: {
        charge_id: params.chargeId,
        org_id: params.orgId,
      },
    })

    if (!session.url) {
      throw new Error('[stripe] Checkout session created without a URL')
    }

    return {
      url: session.url,
      reference: session.id,
    }
  }
}
