/**
 * The shot list — data only, no Playwright imports.
 *
 * Ordered to match docs/video-system-tour-script.md. `nominalMs` is the
 * contract: postprocess trims every clip to exactly nominalMs*30/1000 frames
 * starting at the curtain lift, so the he and en cuts are frame-identical by
 * construction rather than by luck.
 *
 * Selectors go through i18n keys (byKey) because the codebase has no
 * data-testid and every visible string differs between locales.
 */


import { pathToFileURL } from 'node:url'
import { resolve } from 'node:path'

/** Mockups live on disk, generated by scripts/video/whatsapp-mockup.ts. */
const mockUrl = (scene, loc) =>
  pathToFileURL(resolve(`video-assets/whatsapp/${scene}-${loc}.html`)).href

/** Step the chat forward n times, holding between reveals. */
const play = async (m, page, steps) => {
  for (const hold of steps) {
    await page.evaluate(() => window.__wa.next())
    await m.hold(hold)
  }
}

/** The language toggle reads "English" in he and "עברית" in en. */
const localeToggle = (page) =>
  page.locator('button:has-text("English"), button:has-text("עברית")').first()

export const SHOTS = [
  // ── Beat 4 — the dashboard ────────────────────────────────────────────────
  {
    id: 'dash-overview',
    beat: 4,
    shell: 'dashboard',
    route: '/dashboard',
    nominalMs: 6200,
    action: async (m, { page, byKey }) => {
      await m.hold(1400)
      await m.scrollTo(byKey('dashboard.attention.title'), { extra: -110 })
      await m.hold(1600)
    },
  },
  {
    id: 'dash-attention-tick',
    beat: 4,
    shell: 'dashboard',
    route: '/dashboard',
    nominalMs: 9000,
    flags: { toasts: true },
    prep: async ({ page, byKey }) => {
      await byKey('dashboard.attention.title').scrollIntoViewIfNeeded().catch(() => {})
    },
    action: async (m, { page }) => {
      await m.hold(900)
      const box = page.getByRole('checkbox').first()
      await m.click(box, { ms: 780, dwellMs: 320, afterMs: 1900 })
      await m.hold(1200)
    },
  },

  // ── Beat 5 — the calendar ─────────────────────────────────────────────────
  {
    id: 'calendar-week',
    beat: 5,
    shell: 'dashboard',
    route: '/lessons',
    nominalMs: 8000,
    action: async (m, { byKey }) => {
      await m.hold(700)
      await m.click(byKey('lessons.viewWeek', 'button'), { afterMs: 1500 })
      await m.hold(1600)
    },
  },
  {
    id: 'calendar-new-lesson-sheet',
    beat: 5,
    shell: 'dashboard',
    route: '/lessons',
    nominalMs: 11500,
    action: async (m, { byKey }) => {
      await m.hold(600)
      await m.click(byKey('lessons.viewMonth', 'button'), { afterMs: 1400 })
      await m.click(byKey('lessons.newLesson', 'button'), { afterMs: 1800 })
      await m.hold(1200)
    },
  },

  // ── Beat 6 — the billing engine ───────────────────────────────────────────
  {
    id: 'billing-table',
    beat: 6,
    shell: 'dashboard',
    route: '/billing',
    nominalMs: 6200,
    action: async (m) => {
      await m.hold(1600)
      await m.scrollBy(360, 900)
      await m.hold(1800)
    },
  },
  {
    id: 'billing-detail',
    beat: 6,
    shell: 'dashboard',
    route: (deps) => `/billing/${deps.tenant.studentId}`,
    nominalMs: 7000,
    action: async (m) => {
      await m.hold(1500)
      await m.scrollBy(320, 900)
      await m.hold(2200)
    },
  },

  // ── Beat 7 — money out and money owed ─────────────────────────────────────
  {
    id: 'charges',
    beat: 7,
    shell: 'dashboard',
    route: '/charges',
    nominalMs: 6200,
    action: async (m) => {
      await m.hold(1500)
      await m.scrollBy(300, 850)
      await m.hold(1400)
    },
  },
  {
    id: 'debts',
    beat: 7,
    shell: 'dashboard',
    route: '/billing/debts',
    nominalMs: 6600,
    action: async (m) => {
      await m.hold(1600)
      await m.scrollBy(280, 850)
      await m.hold(1600)
    },
  },

  // ── Beat 8 — visibility ───────────────────────────────────────────────────
  {
    id: 'reports-revenue',
    beat: 8,
    shell: 'dashboard',
    route: '/reports/revenue',
    nominalMs: 6400,
    settleMs: 1800,
    action: async (m) => {
      await m.hold(1800)
      await m.scrollBy(260, 850)
      await m.hold(1400)
    },
  },
  {
    id: 'reports-teacher-performance',
    beat: 8,
    shell: 'dashboard',
    route: '/reports/teacher-performance',
    nominalMs: 6000,
    action: async (m) => {
      await m.hold(1500)
      await m.scrollBy(240, 800)
      await m.hold(1200)
    },
  },

  // ── Beat 9 — the parent portal ────────────────────────────────────────────
  {
    id: 'portal-home',
    beat: 9,
    shell: 'portal',
    viewport: 'phone',
    route: (deps) => `/portal/${deps.tenant.orgId}/home`,
    nominalMs: 6600,
    action: async (m) => {
      await m.hold(1600)
      await m.scrollBy(420, 900)
      await m.hold(1600)
    },
  },
  {
    id: 'portal-progress',
    beat: 9,
    shell: 'portal',
    viewport: 'phone',
    route: (deps) => `/portal/${deps.tenant.orgId}/progress`,
    nominalMs: 6000,
    action: async (m) => {
      await m.hold(1500)
      await m.scrollBy(380, 850)
      await m.hold(1300)
    },
  },

  // ── Beat 10 — team, and the same system in two languages ──────────────────
  {
    id: 'teachers',
    beat: 10,
    shell: 'dashboard',
    route: '/teachers',
    nominalMs: 5800,
    action: async (m) => {
      await m.hold(1400)
      await m.scrollBy(220, 800)
      await m.hold(1200)
    },
  },
  {
    id: 'locale-flip',
    beat: 10,
    shell: 'dashboard',
    route: '/dashboard',
    nominalMs: 9400,
    action: async (m, { page }) => {
      await m.hold(1100)
      await m.click(localeToggle(page), { ms: 800, dwellMs: 320, afterMs: 2600 })
      await m.hold(1000)
    },
  },

  // ── Pillar: the parent portal, in depth ───────────────────────────────────
  {
    id: 'portal-homework',
    beat: 9,
    shell: 'portal',
    viewport: 'phone',
    route: (deps) => `/portal/${deps.tenant.orgId}/homework`,
    nominalMs: 6000,
    action: async (m) => {
      await m.hold(1500)
      await m.scrollBy(400, 900)
      await m.hold(1500)
    },
  },
  {
    id: 'portal-payments',
    beat: 9,
    shell: 'portal',
    viewport: 'phone',
    route: (deps) => `/portal/${deps.tenant.orgId}/payments`,
    nominalMs: 5600,
    action: async (m) => {
      await m.hold(1500)
      await m.scrollBy(380, 900)
      await m.hold(1400)
    },
  },
  {
    id: 'portal-book',
    beat: 9,
    shell: 'portal',
    viewport: 'phone',
    route: (deps) => `/portal/${deps.tenant.orgId}/book`,
    nominalMs: 5600,
    action: async (m) => {
      await m.hold(1600)
      await m.scrollBy(300, 850)
      await m.hold(1400)
    },
  },
  {
    id: 'portal-messages',
    beat: 9,
    shell: 'portal',
    viewport: 'phone',
    route: (deps) => `/portal/${deps.tenant.orgId}/messages`,
    nominalMs: 5200,
    action: async (m) => {
      await m.hold(1500)
      await m.scrollBy(280, 800)
      await m.hold(1300)
    },
  },

  // ── Pillar: the teacher side of homework and parent messaging ─────────────
  {
    id: 'homework-board',
    beat: 5,
    shell: 'dashboard',
    route: '/homework',
    nominalMs: 5600,
    action: async (m) => {
      await m.hold(1500)
      await m.scrollBy(300, 850)
      await m.hold(1400)
    },
  },
  {
    id: 'messages-board',
    beat: 9,
    shell: 'dashboard',
    route: '/messages',
    nominalMs: 5200,
    action: async (m) => {
      await m.hold(1500)
      await m.scrollBy(240, 800)
      await m.hold(1300)
    },
  },

  // ── Pillar: onboarding a new customer — the import wizard ─────────────────
  {
    id: 'import-wizard',
    beat: 10,
    shell: 'dashboard',
    route: '/students/import',
    nominalMs: 6000,
    action: async (m) => {
      await m.hold(1600)
      await m.scrollBy(320, 900)
      await m.hold(1500)
    },
  },

  // ── Pillar: the bot runs the operation, hands-free ────────────────────────
  // Mockups, because no real WhatsApp UI can be filmed — but every string in
  // them comes from src/lib/whatsapp, so this is what a parent actually gets.
  {
    id: 'wa-cancel-flow',
    beat: 2,
    shell: 'mockup',
    viewport: 'phone',
    route: (deps) => mockUrl('01-cancel-flow', deps.locale),
    nominalMs: 18000,
    still: 'end',
    action: async (m, { page }) => {
      await m.hold(700)
      await play(m, page, [900, 1500, 1400, 1600, 900, 1400, 1500, 1600, 1200, 900, 2200])
    },
  },
  {
    id: 'wa-copilot',
    beat: 4,
    shell: 'mockup',
    viewport: 'phone',
    route: (deps) => mockUrl('03-copilot', deps.locale),
    nominalMs: 11000,
    action: async (m, { page }) => {
      await m.hold(800)
      await play(m, page, [1400, 1300, 2200, 1200, 2200])
    },
  },
  {
    id: 'wa-payment-request',
    beat: 7,
    shell: 'mockup',
    viewport: 'phone',
    route: (deps) => mockUrl('02-payment-request', deps.locale),
    nominalMs: 9000,
    action: async (m, { page }) => {
      await m.hold(800)
      await play(m, page, [2400, 1400, 2600])
    },
  },
  {
    id: 'wa-booking',
    beat: 3,
    shell: 'mockup',
    viewport: 'phone',
    route: (deps) => mockUrl('04-booking', deps.locale),
    nominalMs: 11000,
    action: async (m, { page }) => {
      await m.hold(800)
      await play(m, page, [1300, 1300, 2200, 1200, 2200])
    },
  },
  // ── Beat 3 — the booking WebView. LAST: it writes a lesson. ───────────────
  {
    id: 'booking-flow',
    beat: 3,
    shell: 'booking',
    viewport: 'phone',
    route: async (deps) => `/book/${await deps.bookingToken(deps.locale)}`,
    nominalMs: 10000,
    action: async (m, { page }) => {
      await m.hold(1500)
      const firstCard = page.locator('button, [role="button"]').filter({ hasText: /\S/ }).nth(1)
      await m.click(firstCard, { ms: 700, afterMs: 1800 }).catch(() => {})
      await m.hold(2200)
    },
  },
]
