/**
 * Registers all Lessio message templates on a newly connected WABA.
 * Called fire-and-forget from saveWhatsAppConnection after Embedded Signup.
 *
 * Templates are UTILITY category — Meta typically auto-approves these within minutes.
 * Duplicate registration is safe: the API returns an error we silently ignore.
 */

import { META_API_VERSION } from './graphVersion'
import { getShareableBaseUrl } from '@/lib/url/appUrl'

type TemplateDefinition = {
  name: string
  language: string
  /** Defaults to UTILITY. AUTHENTICATION templates have a fixed Meta-generated body. */
  category?: 'UTILITY' | 'AUTHENTICATION'
  bodyText?: string
  example?: string[][]
  /**
   * Full components payload override. Used for AUTHENTICATION templates whose
   * body text is generated by Meta and cannot be customised — bodyText/example
   * do not apply there.
   */
  rawComponents?: Record<string, unknown>[]
}

// Copy rewrite (Sprint 32): the `_v2` suffix is deliberate. Editing an already
// approved Meta template resets it to PENDING and blocks out-of-window sends
// until re-approval, so new copy ships under new names and the old templates
// stay live as the fallback until the v2 set is approved.
export const TEMPLATES: TemplateDefinition[] = [
  {
    name: 'lessio_lesson_reminder_he_v2',
    language: 'he',
    bodyText: 'תזכורת: שיעור עם {{1}} מתקיים {{2}} בשעה {{3}}. נתראה!',
    example: [['שרה כהן', 'יום שני 12/5', '16:00']],
  },
  {
    name: 'lessio_payment_reminder_he_v2',
    language: 'he',
    bodyText: 'היי {{1}}, תזכורת קטנה: יש יתרה פתוחה של ₪{{2}}. תודה!',
    example: [['משה לוי', '350']],
  },
  {
    // Meta rejects a variable at the very start or end of the body (2388299),
    // hence the closing line after the link.
    name: 'lessio_payment_request_he_v2',
    language: 'he',
    bodyText: 'היי! התקבלה בקשת תשלום בסך ₪{{1}}.\nלתשלום מאובטח בקישור:\n{{2}}\nתודה רבה!',
    example: [['350', 'https://pay.example.com/abc']],
  },
  {
    name: 'lessio_homework_reminder_he_v2',
    language: 'he',
    bodyText: 'תזכורת: שיעורי הבית של {{1}}, "{{2}}", צריכים להיות מוכנים עד {{3}}. בהצלחה!',
    example: [['דוד כהן', 'פרק ג בספר', '15/5']],
  },
  {
    // Body kept deliberately wordy: Meta rejects templates with too many
    // variables relative to their static text (2388293).
    name: 'lessio_homework_assignment_he_v2',
    language: 'he',
    bodyText:
      'שיעורי בית חדשים ממתינים לכם 📚\nנושא: {{1}}\nפירוט המשימה: {{2}}\nמועד הגשה: {{3}}\nבהצלחה, ונשמח לעדכון כשסיימתם.',
    example: [['חיבור על הקיץ', 'כתיבת חיבור של 300 מילים', 'להגשה עד: 20/5']],
  },
  {
    name: 'lessio_homework_graded_he_v2',
    language: 'he',
    bodyText:
      'שיעורי הבית שלכם נבדקו ✅\nנושא: {{1}}\nציון שהתקבל: {{2}} מתוך 100\n{{3}}\nכל הכבוד על ההשקעה!',
    example: [['חיבור על הקיץ', '92', 'משוב: כתיבה יפה, כל הכבוד!']],
  },
  // ── English set ─────────────────────────────────────────────────────────
  // Parameter order matches the Hebrew templates one-for-one, so the shared
  // buildComponents in approvedTemplates.ts works for both.
  {
    name: 'lessio_lesson_reminder_en_v2',
    language: 'en',
    bodyText: 'Reminder: your lesson with {{1}} is on {{2}} at {{3}}. See you there!',
    example: [['Sarah Cohen', 'Monday 12/5', '16:00']],
  },
  {
    name: 'lessio_payment_reminder_en_v2',
    language: 'en',
    bodyText: 'Hi {{1}}, a small reminder: you have an open balance of ₪{{2}}. Thank you!',
    example: [['Moshe Levi', '350']],
  },
  {
    name: 'lessio_payment_request_en_v2',
    language: 'en',
    bodyText: 'Hi! A payment request for ₪{{1}} is ready.\nYou can pay securely here:\n{{2}}\nThank you very much!',
    example: [['350', 'https://pay.example.com/abc']],
  },
  {
    name: 'lessio_homework_reminder_en_v2',
    language: 'en',
    bodyText: 'Reminder: {{1}}\'s homework, "{{2}}", is due by {{3}}. Good luck!',
    example: [['David Cohen', 'Chapter 3', '15/5']],
  },
  {
    name: 'lessio_homework_assignment_en_v2',
    language: 'en',
    bodyText:
      'New homework is waiting for you 📚\nTopic: {{1}}\nWhat to do: {{2}}\nDue date: {{3}}\nGood luck, and let us know when it is done.',
    example: [['Summer essay', 'Write a 300-word essay', 'Due by: 20/5']],
  },
  {
    name: 'lessio_homework_graded_en_v2',
    language: 'en',
    bodyText:
      'Your homework has been graded ✅\nTopic: {{1}}\nScore received: {{2}} out of 100\n{{3}}\nGreat work, keep it up!',
    example: [['Summer essay', '92', 'Feedback: lovely writing!']],
  },
  // ── Teacher day off ─────────────────────────────────────────────────────
  // The parent notice goes out when an owner approves a teacher's day off, so
  // by definition it is proactive and usually lands outside the 24h window —
  // plain text there fails with 131047. The quick-reply button carries the
  // rebooking offer: Meta stores only the label, and the payload (m:book) is
  // bound at send time, so the tap runs the normal booking flow and mints a
  // fresh 15-minute link. Embedding a link in the body instead would ship an
  // already-expired token.
  {
    name: 'lessio_lesson_cancelled_by_teacher_he_v2',
    language: 'he',
    rawComponents: [
      {
        type: 'BODY',
        text: 'עדכון חשוב: המורה {{1}} לא זמין/ה בתאריכים {{2}}, ולכן השיעורים שנקבעו בתקופה הזו בוטלו. לא יבוצע חיוב על השיעורים האלה, ונשמח לקבוע מועד חלופי.',
        example: { body_text: [['שרה כהן', '20/08–22/08']] },
      },
      {
        type: 'BUTTONS',
        buttons: [{ type: 'QUICK_REPLY', text: 'קביעת שיעור חדש' }],
      },
    ],
  },
  {
    name: 'lessio_lesson_cancelled_by_teacher_en_v2',
    language: 'en',
    rawComponents: [
      {
        type: 'BODY',
        text: 'An important update: {{1}} is unavailable on {{2}}, so the lessons scheduled in that period have been cancelled. You will not be charged for them, and we would be glad to find a new time.',
        example: { body_text: [['Sarah Cohen', '20/08–22/08']] },
      },
      {
        type: 'BUTTONS',
        buttons: [{ type: 'QUICK_REPLY', text: 'Book a new lesson' }],
      },
    ],
  },
  {
    // The decision can land days after the teacher last wrote in, so this needs
    // a template too rather than plain text.
    name: 'lessio_day_off_decision_he_v2',
    language: 'he',
    bodyText: 'עדכון לגבי בקשת החופש שלך לתאריכים {{1}}: הבקשה {{2}}. תודה!',
    example: [['20/08–22/08', 'אושרה']],
  },
  {
    name: 'lessio_day_off_decision_en_v2',
    language: 'en',
    bodyText: 'An update on your time-off request for {{1}}: the request was {{2}}. Thank you!',
    example: [['20/08–22/08', 'approved']],
  },
  // ── Welcome notice (opt-in) ─────────────────────────────────────────────
  // Sent once, before the first business-initiated message a parent ever gets
  // from this number (src/lib/whatsapp/consent.ts). By definition that is a
  // cold start outside the 24h window, so it has to be a template. {{1}} is
  // the business name, kept mid-sentence because Meta rejects a variable at
  // the very start or end of the body.
  {
    name: 'lessio_welcome_notice_he_v2',
    language: 'he',
    bodyText:
      'שלום! ההודעות בערוץ זה נשלחות מטעם {{1}} באמצעות Lessio — תזכורות לשיעורים, שיעורי בית ובקשות תשלום. אפשר להפסיק אותן בכל עת בתשובה "הסר".',
    example: [['מרכז הלמידה של אהרון']],
  },
  {
    name: 'lessio_welcome_notice_en_v2',
    language: 'en',
    bodyText:
      'Hi! Messages in this chat are sent on behalf of {{1}} via Lessio — lesson reminders, homework and payment requests. Reply "stop" at any time to opt out.',
    example: [['Brightpath Tutoring']],
  },
  // ── Menu with quick-reply buttons ───────────────────────────────────────
  // Free-form interactive messages are rejected outside the 24h window, so the
  // tappable menu needs a template twin. Meta stores only the labels; the
  // payloads (m:book / m:cancel / m:balance) are bound at send time and come
  // back in button.payload. Three buttons is Meta's hard cap.
  {
    name: 'lessio_menu_he_v2',
    language: 'he',
    rawComponents: [
      {
        type: 'BODY',
        text: 'היי {{1}} 👋 איך אפשר לעזור? אפשר לבחור אחת מהאפשרויות למטה, או פשוט לכתוב לנו מה צריך.',
        example: { body_text: [['יעל']] },
      },
      {
        type: 'BUTTONS',
        buttons: [
          { type: 'QUICK_REPLY', text: 'קביעת שיעור' },
          { type: 'QUICK_REPLY', text: 'ביטול שיעור' },
          { type: 'QUICK_REPLY', text: 'יתרה ותשלום' },
        ],
      },
    ],
  },
  {
    // _v3, and with no {{1}}: names are stored in Hebrew, so the v2 body put
    // "Hi יעל 👋" in front of English speakers. Editing an approved template
    // resets it to PENDING, hence a new name rather than a body change.
    // A template with no variables at all is fine — what Meta rejects is a
    // variable at the very start or end of the body.
    name: 'lessio_menu_en_v3',
    language: 'en',
    rawComponents: [
      {
        type: 'BODY',
        text: 'Hi 👋 How can I help? Pick one of the options below, or just tell us what you need.',
      },
      {
        type: 'BUTTONS',
        buttons: [
          { type: 'QUICK_REPLY', text: 'Book a lesson' },
          { type: 'QUICK_REPLY', text: 'Cancel a lesson' },
          { type: 'QUICK_REPLY', text: 'Balance & payment' },
        ],
      },
    ],
  },
  // ── Button-carrying reminders (v3) ──────────────────────────────────────
  // Same bodies as the v2 set above, plus the buttons that turn a reminder into
  // something a parent can act on with one tap. New names, not edits: editing
  // an approved template resets it to PENDING and blocks out-of-window sends,
  // so v2 stays live as the no-button fallback until these are approved.
  //
  // Meta stores only the labels. The payloads (att:ok:<lessonId>,
  // hw:done:<assignmentId>) are bound at send time and come back in
  // button.payload, so one approved template serves every lesson.
  {
    name: 'lessio_lesson_reminder_he_v3',
    language: 'he',
    rawComponents: [
      {
        type: 'BODY',
        text: 'תזכורת: שיעור עם {{1}} מתקיים {{2}} בשעה {{3}}. נתראה!',
        example: { body_text: [['שרה כהן', 'יום שני 12/5', '16:00']] },
      },
      {
        type: 'BUTTONS',
        buttons: [
          { type: 'QUICK_REPLY', text: 'מאשר/ת הגעה' },
          { type: 'QUICK_REPLY', text: 'צריך לבטל' },
        ],
      },
    ],
  },
  {
    name: 'lessio_lesson_reminder_en_v3',
    language: 'en',
    rawComponents: [
      {
        type: 'BODY',
        text: 'Reminder: your lesson with {{1}} is on {{2}} at {{3}}. See you there!',
        example: { body_text: [['Sarah Cohen', 'Monday 12/5', '16:00']] },
      },
      {
        type: 'BUTTONS',
        buttons: [
          { type: 'QUICK_REPLY', text: 'Confirm attendance' },
          { type: 'QUICK_REPLY', text: 'Need to cancel' },
        ],
      },
    ],
  },
  {
    name: 'lessio_homework_assignment_he_v3',
    language: 'he',
    rawComponents: [
      {
        type: 'BODY',
        text: 'שיעורי בית חדשים ממתינים לכם 📚\nנושא: {{1}}\nפירוט המשימה: {{2}}\nמועד הגשה: {{3}}\nבהצלחה, ונשמח לעדכון כשסיימתם.',
        example: {
          body_text: [['חיבור על הקיץ', 'כתיבת חיבור של 300 מילים', 'להגשה עד: 20/5']],
        },
      },
      // No emoji in a button label: Meta rejects the whole template ("buttons
      // cannot contain variables, newlines, emoji or formatting characters").
      { type: 'BUTTONS', buttons: [{ type: 'QUICK_REPLY', text: 'סיימתי' }] },
    ],
  },
  {
    name: 'lessio_homework_assignment_en_v3',
    language: 'en',
    rawComponents: [
      {
        type: 'BODY',
        text: 'New homework is waiting for you 📚\nTopic: {{1}}\nWhat to do: {{2}}\nDue date: {{3}}\nGood luck, and let us know when it is done.',
        example: { body_text: [['Summer essay', 'Write a 300-word essay', 'Due by: 20/5']] },
      },
      { type: 'BUTTONS', buttons: [{ type: 'QUICK_REPLY', text: 'Done' }] },
    ],
  },
  {
    name: 'lessio_homework_reminder_he_v3',
    language: 'he',
    rawComponents: [
      {
        type: 'BODY',
        text: 'תזכורת: שיעורי הבית של {{1}}, "{{2}}", צריכים להיות מוכנים עד {{3}}. בהצלחה!',
        example: { body_text: [['דוד כהן', 'פרק ג בספר', '15/5']] },
      },
      // No emoji in a button label: Meta rejects the whole template ("buttons
      // cannot contain variables, newlines, emoji or formatting characters").
      { type: 'BUTTONS', buttons: [{ type: 'QUICK_REPLY', text: 'סיימתי' }] },
    ],
  },
  {
    name: 'lessio_homework_reminder_en_v3',
    language: 'en',
    rawComponents: [
      {
        type: 'BODY',
        text: 'Reminder: {{1}}\'s homework, "{{2}}", is due by {{3}}. Good luck!',
        example: { body_text: [['David Cohen', 'Chapter 3', '15/5']] },
      },
      { type: 'BUTTONS', buttons: [{ type: 'QUICK_REPLY', text: 'Done' }] },
    ],
  },
  // ── Payment messages with a pay button (v3) ─────────────────────────────
  // The body drops the bare link the v2 copy carried; the URL button takes its
  // place. Meta only accepts a dynamic SUFFIX on a fixed base, and a provider
  // link's domain varies per org, so the button points at our own /pay/<id>
  // redirect. That bakes this deployment's origin into the approved template:
  // an org on a different domain would need its own registration.
  ...paymentButtonTemplates(),
  {
    // Portal OTP login (Sprint 31). Body copy is fixed by Meta for AUTHENTICATION
    // templates; the footer expiry must match the 10-minute OTP TTL in
    // src/lib/portal/otp.ts. Sent via src/lib/whatsapp/sendOtp.ts.
    name: 'lessio_otp_he',
    language: 'he',
    category: 'AUTHENTICATION',
    rawComponents: [
      { type: 'BODY', add_security_recommendation: true },
      { type: 'FOOTER', code_expiration_minutes: 10 },
      // No custom button `text`: Meta rejects it (2388060) and generates the
      // localised "copy code" label itself from the template language.
      { type: 'BUTTONS', buttons: [{ type: 'OTP', otp_type: 'COPY_CODE' }] },
    ],
  },
  {
    name: 'lessio_otp_en',
    language: 'en',
    category: 'AUTHENTICATION',
    rawComponents: [
      { type: 'BODY', add_security_recommendation: true },
      { type: 'FOOTER', code_expiration_minutes: 10 },
      { type: 'BUTTONS', buttons: [{ type: 'OTP', otp_type: 'COPY_CODE' }] },
    ],
  },
]

/**
 * The four payment templates that carry a pay button.
 *
 * Built rather than written out because the button URL has to be resolved from
 * this deployment's origin, and all four differ only in copy.
 */
function paymentButtonTemplates(): TemplateDefinition[] {
  const payBase = `${getShareableBaseUrl()}/pay/`
  const urlButton = (text: string) => ({
    type: 'BUTTONS',
    buttons: [
      {
        type: 'URL',
        text,
        url: `${payBase}{{1}}`,
        example: [`${payBase}3f2b8a1c-9d4e-4f6a-8b2c-1e5d7a9c3b0f`],
      },
    ],
  })

  return [
    {
      name: 'lessio_payment_request_he_v3',
      language: 'he',
      rawComponents: [
        {
          type: 'BODY',
          text: 'היי! התקבלה בקשת תשלום בסך ₪{{1}}.\nאפשר לשלם בבטחה בכפתור שלמטה. תודה רבה!',
          example: { body_text: [['350']] },
        },
        urlButton('לתשלום מאובטח'),
      ],
    },
    {
      name: 'lessio_payment_request_en_v3',
      language: 'en',
      rawComponents: [
        {
          type: 'BODY',
          text: 'Hi! A payment request for ₪{{1}} is ready.\nYou can pay securely using the button below. Thank you very much!',
          example: { body_text: [['350']] },
        },
        urlButton('Pay securely'),
      ],
    },
    {
      name: 'lessio_payment_reminder_he_v3',
      language: 'he',
      rawComponents: [
        {
          type: 'BODY',
          text: 'היי {{1}}, תזכורת קטנה: יש יתרה פתוחה של ₪{{2}}. אפשר לשלם בכפתור שלמטה. תודה!',
          example: { body_text: [['משה לוי', '350']] },
        },
        urlButton('לתשלום מאובטח'),
      ],
    },
    {
      name: 'lessio_payment_reminder_en_v3',
      language: 'en',
      rawComponents: [
        {
          type: 'BODY',
          text: 'Hi {{1}}, a small reminder: you have an open balance of ₪{{2}}. You can pay using the button below. Thank you!',
          example: { body_text: [['Moshe Levi', '350']] },
        },
        urlButton('Pay securely'),
      ],
    },
  ]
}

/**
 * Registers every template on a WABA. Never throws — this runs fire-and-forget
 * from the signup flow, where a template failure must not break the connection.
 * Returns the per-template outcome so callers that DO care (the rollout script)
 * can report it instead of assuming success.
 */
export async function registerTemplatesForWABA(
  wabaId: string,
  accessToken: string
): Promise<{ ok: string[]; failed: Array<{ name: string; reason: string }> }> {
  const results = await Promise.allSettled(
    TEMPLATES.map((t) => registerOne(wabaId, accessToken, t))
  )

  const ok: string[] = []
  const failed: Array<{ name: string; reason: string }> = []

  results.forEach((r, i) => {
    const name = TEMPLATES[i].name
    if (r.status === 'fulfilled') ok.push(name)
    else failed.push({ name, reason: r.reason instanceof Error ? r.reason.message : String(r.reason) })
  })

  if (failed.length > 0) {
    console.warn(
      `[registerTemplates] ${failed.length}/${TEMPLATES.length} templates failed for WABA ${wabaId}`,
      failed
    )
  } else {
    console.info(
      `[registerTemplates] All ${TEMPLATES.length} templates registered for WABA ${wabaId}`
    )
  }

  return { ok, failed }
}

/** Outcome of a single POST to Meta's message_templates endpoint. */
export type PostTemplateResult =
  /** Meta accepted the template; it is now PENDING (or auto-approved) at Meta. */
  | { outcome: 'created'; id: string | null }
  /** A template with this name/language/content is already registered on the WABA. */
  | { outcome: 'exists'; detail: string }
  /** Meta rejected it. `userMessage` is Meta's own explanation, safe to show a user. */
  | { outcome: 'error'; status: number; body: string; userMessage: string | null }

/**
 * POSTs one template to a WABA and classifies the response.
 *
 * Shared by the built-in registry rollout (registerOne, below) and by
 * org-authored submissions from the settings page (src/lib/whatsapp/submitTemplate.ts),
 * so both benefit from the duplicate/category subcode handling learned here.
 * Never throws on an HTTP-level rejection — it reports; callers decide.
 */
export async function postTemplateToMeta(
  wabaId: string,
  accessToken: string,
  template: {
    name: string
    language: string
    category?: 'UTILITY' | 'AUTHENTICATION'
    components: Record<string, unknown>[]
  }
): Promise<PostTemplateResult> {
  const res = await fetch(
    `https://graph.facebook.com/${META_API_VERSION}/${wabaId}/message_templates`,
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: template.name,
        language: template.language,
        category: template.category ?? 'UTILITY',
        components: template.components,
      }),
    }
  )

  const body = await res.text().catch(() => '')

  if (res.ok) {
    let id: string | null = null
    try {
      id = (JSON.parse(body) as { id?: string }).id ?? null
    } catch {
      // A 2xx with an unparseable body still means Meta accepted it.
    }
    return { outcome: 'created', id }
  }

  // Template already exists — not an error. Match on Meta's numeric subcode
  // (2388024 = "content already exists in this language"), never on the message
  // text: Meta localises error_user_msg to the account language, so the old
  // English substring check reported every duplicate as a hard failure.
  if (
    body.includes('"error_subcode":2388024') ||
    body.includes('duplicate') ||
    body.includes('already exists') ||
    res.status === 409
  ) {
    return { outcome: 'exists', detail: 'duplicate' }
  }

  // 2388026: the template exists, but Meta assigned it a different category than
  // the one we asked for (it re-classifies menu-style copy as MARKETING). The
  // category of an existing template cannot be changed by re-POSTing, so this is
  // an "exists" outcome, not a failure — reporting it as one made every rerun of
  // the rollout script look broken.
  if (body.includes('"error_subcode":2388026')) {
    return { outcome: 'exists', detail: 'different_category' }
  }

  return { outcome: 'error', status: res.status, body, userMessage: extractUserMessage(body) }
}

/**
 * Pulls Meta's human-readable rejection text out of an error response.
 * `error_user_msg` is written for an end user (and localised to the account
 * language); `message` is the developer-facing fallback.
 */
export function extractUserMessage(body: string): string | null {
  try {
    const parsed = JSON.parse(body) as {
      error?: { error_user_msg?: string; error_user_title?: string; message?: string }
    }
    return parsed.error?.error_user_msg ?? parsed.error?.message ?? null
  } catch {
    return null
  }
}

async function registerOne(
  wabaId: string,
  accessToken: string,
  template: TemplateDefinition
): Promise<void> {
  const result = await postTemplateToMeta(wabaId, accessToken, {
    name: template.name,
    language: template.language,
    category: template.category,
    components: template.rawComponents ?? [
      {
        type: 'BODY',
        text: template.bodyText,
        example: { body_text: template.example },
      },
    ],
  })

  if (result.outcome === 'created') {
    console.info(`[registerTemplates] Registered: ${template.name}`)
    return
  }

  if (result.outcome === 'exists') {
    console.info(
      result.detail === 'different_category'
        ? `[registerTemplates] Already exists with a different category: ${template.name}`
        : `[registerTemplates] Already exists: ${template.name}`
    )
    return
  }

  // The raw body (with fbtrace_id etc.) goes to the log; the thrown reason is
  // Meta's human-readable explanation, because RegisterTemplatesButton renders
  // it verbatim to the user.
  console.warn(`[registerTemplates] Failed ${template.name}: ${result.status} ${result.body}`)
  throw new Error(result.userMessage ?? `HTTP ${result.status}`)
}
