-- Storage bucket for the tax invoices and credit notes generated by
-- src/lib/billing/invoices/.
--
-- The feature shipped in Sprint 27 without this bucket ever being created.
-- Every other bucket in the product (homework-media, progress-reports,
-- exam-files) is provisioned by its own migration; this one was not, so
-- uploadInvoicePdf has always failed with "Bucket not found". Approval calls
-- invoice generation fire-and-forget, so the failure was invisible: no org has
-- ever received an invoice PDF. Found by UX audit 8 (F-C1), alongside a
-- separate bug in the generators' SELECT columns fixed in the same change.
--
-- Private, like every other bucket here: invoices are served through short-lived
-- signed URLs (getInvoiceSignedUrl), never by public path. Access is via the
-- service-role client only — the dashboard reaches it through a server action
-- that has already resolved the org from the session — so no storage RLS policy
-- is added, matching progress-reports and exam-files.

INSERT INTO storage.buckets (id, name, public)
VALUES ('invoices', 'invoices', false)
ON CONFLICT (id) DO NOTHING;
