-- Charge notes generated by syncMonthlyCharge were stored as Hebrew display
-- copy ("חיוב חודשי 2026-04"). They are written once and read much later,
-- possibly by a user working in English, so the generated ones are now stored
-- as a stable code and translated at render time (src/lib/charges/renderNote.ts).
--
-- Backfills existing rows. Free-text notes typed by a user are left alone —
-- only the exact generated shape is rewritten.

UPDATE charges
SET notes = 'MONTHLY_CHARGE:' || substring(notes from '^חיוב חודשי (\d{4}-\d{2})$')
WHERE notes ~ '^חיוב חודשי \d{4}-\d{2}$';
